//You are given two strings s and t. 
//
// String t is generated by random shuffling string s and then add one more 
//letter at a random position. 
//
// Return the letter that was added to t. 
//
// 
// Example 1: 
//
// 
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
// 
//
// Example 2: 
//
// 
//Input: s = "", t = "y"
//Output: "y"
// 
//
// 
// Constraints: 
//
// 
// 0 <= s.length <= 1000 
// t.length == s.length + 1 
// s and t consist of lowercase English letters. 
// 
// Related Topics Hash Table String Bit Manipulation Sorting 👍 2890 👎 388


import java.util.HashMap;

//leetcode submit region begin(Prohibit modification and deletion)
class Solution {
    public char findTheDifference(String s, String t) {
        int temp1 = 0;
        int temp2 = 0;

        for (int i = 0; i < s.length(); i++) {
            temp1 = s.charAt(i) + temp1;
        }
        for (int i = 0; i < t.length(); i++) {
            temp2 = t.charAt(i) + temp2;
        }
        temp2 = temp2 - temp1;
        return (char) temp2;

    }
}
//leetcode submit region end(Prohibit modification and deletion)
